services:

  backend:
    build: 
      dockerfile: Dockerfile
      context: ./backend
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:${DATABASE_PORT}/${DATABASE_NAME}
    ports:
      - 3000:8000

  frontend:
    build: 
      dockerfile: Dockerfile
      context: ./frontend

  nginx:
      image: nginx:stable-alpine
      ports:
        - 8080:80
      volumes:
        - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      depends_on:
        - backend
        - frontend
  
  database:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_task
    ports:
      - 5432:5432